### PR TITLE
Next

### PR DESCRIPTION
**Pull request by roastlechon**
falcor-koa-router support for koa@next

### CODE REVIEW

**Comment by yiminghe** [comment]
- this is breaking change, version should be 0.2.0
- do not submit lib to git
- please rebase

**Comment by roastlechon** [comment]
> this is breaking change, version should be 0.2.0

Should we consider major version as 2.0.0 instead?

> do not submit lib to git

lib is transpiled from ES2015 src. I am not sure if publishing a library thats only compatible via babel is okay. I am positive the lib works without ES2015 since its transpiled down to generators and I have also tested the lib with async/awaits.

> please rebase

Why exactly do I need to rebase? Is it just to have a clean history of this PR to one commit?

**Comment by roastlechon** [comment]
I took a peek at another library and now feel slightly more comfortable with publishing just ES2015 into the repo. https://github.com/kadirahq/npm-base

**Comment by yiminghe** [comment]
I have created next branch, can you pr to that branch? as koa2 is still alpha.

Nodejs support different es version between different node versions(4,5,6), it is safe to transpile.

As a convention, transpiled source should be inside lib dir.

**Comment by roastlechon** [comment]
Took me a while (busy with work), but I changed the directory it transpiles to be `lib` instead of `dist`. The `src` folder is still the same in the repo.

**Pull request closed without merging**
